### ISSUE TITLE
WorkflowServiceInstanceService logs unredacted request

### ISSUE THREAD

**Issue by spikymonkey** [spring-cloud/spring-cloud-app-broker#252] opened 2019-06-26 12:58 UTC
I noticed a private key being logged out while testing today. It turned out to be coming from App Broker in the case where service instance creation fails. It's not safe in the general case to log the request here, since it may contain credentials.

```
2019-06-26 12:47:17.632 ERROR 7 --- [ry-client-nio-2] o.s.c.a.s.WorkflowServiceInstanceService : Error creating service instance ServiceBrokerRequest{platformInstanceId='null', apiInfoLocation='api.cf.purple.springapps.io/v2/info', origin
atingIdentity=null}AsyncServiceBrokerRequest{asyncAccepted=true}AsyncParameterizedServiceInstanceRequest{parameters={git={uri=https://scs-gitlab.springapps.io/acceptance/backup-test.git, privateKey=-----BEGIN RSA PRIVATE KEY-----...
```

**Comment by royclarkson** [comment] 2019-10-30 19:42
duplicate of #278. resolved in #279.

**Closed by royclarkson** 2019-10-30 19:42 UTC
